### ISSUE TITLE
Github add 2FA

### ISSUE THREAD

**Issue by henridwyer** [dataiku/dataiku-contrib#14]
@jrouquie it seems like pygithub does support this. Perhaps we could add an optional argument

**Comment by jrouquie** [comment]
https://developer.github.com/v3/auth/ says about 2FA «Because these authentication codes expire quickly, we recommend using the Authorizations API to create an access token and using that token to authenticate via OAuth for most API access.»
Now, OAuth is intended for applications acquiring a token programmatically. I don't think DSS can open a github hosted page for authentication, with a callback to store the token in DSS. Fortunately, Github made things simple, and you can generate a token on https://github.com/settings/tokens .  Then simply use this token instead of your password. Would that work for your use case?

**Comment by cstenac** [comment]
will be enough indeed
