### ISSUE TITLE
Google sheet plugin retrieve column in the wrong order

### ISSUE THREAD

**Issue by PGuti** [dataiku/dataiku-contrib#55]
@jereze 
<img width="1271" alt="screen shot 2017-10-31 at 10 22 00" src="https://user-images.githubusercontent.com/5311307/32216482-6299c260-be25-11e7-84b0-af92731ab1ab.png">

<img width="1278" alt="screen shot 2017-10-31 at 10 21 49" src="https://user-images.githubusercontent.com/5311307/32216475-5fa662ca-be25-11e7-8c41-c6d8920b42bc.png">

**Comment by tgb417** [comment]
First Thank you for this plugin.  It is very nice to have.
I'll +1 this one as well.  I'm having the same problem with the order of the columns coming in from Google Sheets not showing up in the correct order in Dataiku DSS using this plugin.  This can be adjusted but does add an extra step.  This is with DSS 5.0.1 and plugin version 0.1.1.
The Python environment is 
/Users/MYNAME/Library/DataScienceStudio/dss_home/bin/pip install 'gspread==0.4.0' 'oauth2client>=2.0.0,<2.3.0' 'PyOpenSSL>=0.15.0' 'awesome-slugify>=1.6.5'

**Comment by tgb417** [comment]
For Column headers, I'm seeing a lot of unexpected changes between what is in the Google Sheet and what eventually shows up in DSS.

Special Characters like ( ) ? seem to be removed.  These are very common when using Google Forms to gather participant input.

Also, spaces are being changed to underscore.

Also, characters between square brackets [ ] are being removed with the Square brackets.

This can be worked around by building a script step once the data is in DSS but does take extra effort.

**Comment by jereze** [comment]
Hi @tgb417,

Thank you for your feedbacks.

About the order of the columns, that's because the plugin does not know in advance the schema of the spreadsheet and the schema is fixed when fetching the data, and the order might not be respected by Dataiku DSS. I could try to improve this but that could make the plugin slower. I will have a look at it.

For the normalization of the columns names, that's intentional. Some databases does not accept special characters (including spaces).

**Comment by tgb417** [comment]
Jeremy,

Thank you so much for getting back to me!

The bottom line, is that the Microsoft XL import process has a somewhat
different user experience than the Google sheets plug-in for what is the
same spreadsheet. And I guess I think of both of them as spreadsheets, and
therefore they should  work the same. I understand that the Google sheets
plug-in is not fully supported. So whatever is possible is great! It’s so
nice to have a plug-in as it is today. Thank you for sharing. Let me know
if there’s anything that I can do to help.

—Tom
Tgb417@gmail.com


On Sep 20, 2018 at 4:06 AM, Jeremy Greze <notifications@github.com> wrote:


Hi @tgb417 <https://github.com/tgb417>,

Thank you for your feedbacks.

About the order of the columns, that's because the plugin does not know in
advance the schema of the spreadsheet and the schema is fixed when fetching
the data, and the order might not be respected by Dataiku DSS. I could try
to improve this but that could make the plugin slower. I will have a look
at it.

For the normalization of the columns names, that's intentional. Some
databases does not accept special characters (including spaces).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dataiku/dataiku-contrib/issues/55#issuecomment-423083908>,
or mute the thread

**Comment by jereze** [comment]
Hi @tgb417, the [version 1.0.0](https://github.com/dataiku/dataiku-contrib/pull/100) of the plugin fixed this issue. It will be soon published on the plugin store.

**Comment by tgb417** [comment]
Cool.  I've downloaded it from the Plug-In Store.  Have not gotten a moment to test.  Will provide additional feedback if I find anything else.  The is so useful to have.  Thanks.
