### ISSUE TITLE
2000 lines limit

### ISSUE THREAD

**Issue by LucasLf** [dataiku/dataiku-contrib#73]
Hi,
First, thank you for this amazing google sheet connector.
This is not really an issue but the 2000 lines limit you set is really low.
Indeed, we want to write more than 7500 lines in a spreadsheet but we can't due to this limit.
The error : `Failed to write rows : <type 'exceptions.Exception'> : A spreadsheet cannot contain more than 2000 lines.`
Could you increase this limit ? I could download your plugin and do it by myself but it would be no longer up to date with yours.
Thanks in advance.

**Comment by jereze** [comment]
Hi Lucas,

I added this hard limit 2 years ago because, empirically, the recipe could fail when writing more than 2000 lines to a spreadsheet  There might be a limit on the Google API side (if I remember well, there is a documented limit on the number of cells).

You can increase this limit by modifying the file `DATA_DIR/plugins/installed/googlesheets/python-connectors/googlesheets-sheet/connector.py`. You can change [this variable](https://github.com/dataiku/dataiku-contrib/blob/master/googlesheets/python-connectors/googlesheets-sheet/connector.py#L129). Let me know how that works for you.

I plan to rewrite this plugin in the coming weeks. My plan is to use a newer version of the API (Google Sheets API v4) and review all the limits.

**Comment by LucasLf** [comment]
Hi Jeremy,
Thanks for your answer.
Yes, that's what I did and it works well.
Great, I prefer using unmodified extension!

**Comment by jereze** [comment]
Hi @LucasLf, this is now fixed in the [1.0.0 version](https://github.com/dataiku/dataiku-contrib/pull/100).
