### ISSUE TITLE
Salesforce plugin - dataset creation

### ISSUE THREAD

**Issue by BGermonpre** [dataiku/dataiku-contrib#84]
I'm not able to create a dataset from the Salesforce plugin when I choose the option "Readable with columns". More precisely, I cannot build the schema.

Error message: Test failed: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NULL at line 1 column 16 path $.schema, caused by: IllegalStateException: Expected BEGIN_OBJECT but was NULL at line 1 column 16 path $.schema

I can see the data in preview and it also works when I select "JSON" as the format, so I assume my connection has been set up correctly.

Anyone knows how to troubleshoot this? @jereze? 

Thanks!

**Comment by jereze** [comment]
Hi Benoit,

Indeed, it seems that the connection works. Your problem seems specific to the output format with all columns.

I'm not able to reproduce. Can you please share the following information?

- Which version of Dataiku DSS?
- Which version of the plugin?
- Which dataset?
- What data are you fetching from Salesforce? If you try another Salesforce object or another plugin dataset, do you still have the issue?
- How many columns? Anything special in the columns names? A special character?

As a workaround, you can use the JSON output format and then use a prepare recipe to parse the JSON.

**Comment by BGermonpre** [comment]
Thanks for the quick reply.

- DSS version: 5.0.0 (free edition)
- Note: I'm running on Windows via Docker
- Plugin version: 1.1.0
- I have the same issue for all types of data that I'm trying to fetch (object list, records of specific objects)
- Example: Opportunity dataset contains 45 columns and 934 rows. There is nothing special/unique about them.

**Comment by jereze** [comment]
Can you upgrade to 5.0.1 or 5.0.2? I know that a bug around plugin datasets was fixed. It might help.

**Comment by BGermonpre** [comment]
Thanks for the info!
I will use your workaround solution for now. It seems very easy and I'm only testing some functionality for now, so it will be sufficient.
